### ISSUE TITLE
get NLCD data for NEON sites

### ISSUE THREAD

**Issue by reblake** [SESYNC-ci/neon-workshop-data#2]
Start with Kelly's code https://github.com/ecodasXIII/StoichPatterns/blob/master/nlcd_feddata.Rmd and get NLCD data downloaded and subset.

**Comment by khondula** [comment]
2099e3fa1df40bf27e069c1d97da076462e695d4

2016 for lower 48, 2011 for AK and only 2001 available for PR and HI
